import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navegacao } from './components/Navegacao'
import { Footer } from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
        <body className={inter.className}>
          <Navegacao />
          {children}
          <Footer />
        </body>
    </html>
  )
}
