# Generated by Django 5.0.3 on 2024-05-06 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', default='', max_length=100, unique=True)),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=60)),
                ('sobrenome', models.CharField(blank=True, db_column='sobrenome', max_length=60)),
                ('descricao', models.TextField(blank=True, db_column='descricao', max_length=240)),
                ('cpf', models.CharField(blank=True, db_column='cpf', max_length=11, null=True, unique=True)),
                ('endereco_id', models.IntegerField(blank=True, db_column='endereco_id', null=True)),
                ('contato', models.CharField(blank=True, db_column='contato', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Numero de telefone deve conter DDD e 9 ou 8 digitos a mais.', regex='^\\d{10,11}$')])),
                ('email', models.EmailField(db_column='email', max_length=50, unique=True)),
                ('email_verificado', models.BooleanField(db_column='email_verificado', default=False)),
                ('senha', models.CharField(blank=True, db_column='senha', max_length=50)),
                ('foto', models.ImageField(blank=True, db_column='foto', null=True, upload_to='fotos/')),
                ('perfil_acesso', models.CharField(blank=True, db_column='perfil_acesso', max_length=1)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
