# Generated by Django 5.0.3 on 2024-05-14 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='USUARIO',
        ),
    ]
