-- CREATE
-- DATABASE MIAUDOTE;


CREATE TABLE IF NOT EXISTS USUARIO
(
    USUARIO_ID       INTEGER      NOT NULL PRIMARY KEY AUTOINCREMENT,
    USERNAME         VARCHAR(100) NOT NULL,
    NOME             VARCHAR(60)  NOT NULL,
    SOBRENOME        VARCHAR(60)  NOT NULL,
    CPF              VARCHAR(11)  NOT NULL,
    EMAIL            VARCHAR(50)  NOT NULL,
    SENHA            VARCHAR(60)  NOT NULL,
    ENDERECO_ID      INTEGER,
    FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ENDERECO_ID),
    CONTATO          VARCHAR(15),
    PERFIL_ACESSO    CHAR(1),
    FOTO             BLOB,
    DESCRICAO        VARCHAR(240),
    EMAIL_VERIFICADO BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS PET
(
    PET_ID              INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,
    NOME                VARCHAR(50) NOT NULL,
    SEXO                CHAR(1)     NOT NULL,
    IDADE               INTEGER,
    PORTE               CHAR(1),
    CASTRADO            CHAR(1),
    DATA_CADASTRO       DATE        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DESCRICAO           VARCHAR(240),
    FOTO                BLOB,
    USUARIO_CADASTRO_ID INTEGER     NOT NULL,
    FOREIGN KEY (USUARIO_CADASTRO_ID) REFERENCES USUARIO (USUARIO_ID)
);

CREATE TABLE IF NOT EXISTS ENDERECO
(
    ENDERECO_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    ESTADO_ID   INTEGER,
    FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO (ESTADO_ID),
    CIDADE_ID   INTEGER,
    FOREIGN KEY (CIDADE_ID) REFERENCES CIDADE (CIDADE_ID),
    BAIRRO_ID     VARCHAR(100),
    FOREIGN KEY (BAIRRO_ID) REFERENCES BAIRRO (BAIRRO_ID)
);

CREATE TABLE Estado
(
    ESTADO_ID INTEGER         NOT NULL PRIMARY KEY AUTOINCREMENT,
    CODIGO_UF  INTEGER         NOT NULL,
    NOME      VARCHAR(50) NOT NULL,
    UF        CHAR(2)     NOT NULL,
    REGIAO    INTEGER         NOT NULL
);

CREATE TABLE CIDADE
(
    CIDADE_ID INTEGER          NOT NULL PRIMARY KEY AUTOINCREMENT,
    CODIGO    INTEGER          NOT NULL,
    NOME      VARCHAR(255) NOT NULL,
    UF        CHAR(2)      NOT NULL
);
CREATE TABLE BAIRRO (
  BAIRRO_ID 	 INTEGER 		  NOT NULL PRIMARY KEY AUTOINCREMENT,
  CODIGO CHAR(10)	  NOT NULL,
  NOME 	 VARCHAR(255) NOT NULL,
  UF	 CHAR(2)	  NOT NULL
);

CREATE TABLE IF NOT EXISTS DOENCA
(
    DOENCA_ID INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,
    PET_ID    INTEGER,
    FOREIGN KEY (PET_ID) REFERENCES PET (PET_ID),
    NOME      VARCHAR(60) NOT NULL,
    DESCRICAO VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS SOLICITACAO_ADOCAO
(
    SOLICITACAO_ADOCAO_ID          INTEGER   NOT NULL PRIMARY KEY AUTOINCREMENT,
    USER_RESPONSAVEL_ID            INTEGER   NOT NULL,
    FOREIGN KEY (USER_RESPONSAVEL_ID) REFERENCES USUARIO (USUARIO_ID),
    USER_ADOTANTE_ID               INTEGER   NOT NULL,
    FOREIGN KEY (USER_ADOTANTE_ID) REFERENCES USUARIO (USUARIO_ID),
    DATA_SOLICITACAO               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_RESPOSTA_USER_ADOTANTE    TIMESTAMP,
    RESPOSTA_USER_ADOTANTE         CHAR(1),
    DATA_RESPOSTA_USER_RESPONSAVEL TIMESTAMP,
    RESPOSTA_USER_RESPONSAVEL      CHAR(1),
    PET_ID                         INTEGER   NOT NULL,
    FOREIGN KEY (PET_ID) REFERENCES PET (PET_ID)
);

CREATE TABLE IF NOT EXISTS ADOCAO
(
    ADOCAO_ID               INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    DATA_INICIO_ADOCAO      DATE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_ADOCAO_ID          INTEGER NOT NULL,
    FOREIGN KEY (USER_ADOCAO_ID) REFERENCES USUARIO (USUARIO_ID),
    PET_ADOTADO_ID          INTEGER NOT NULL,
    FOREIGN KEY (PET_ADOTADO_ID) REFERENCES PET (PET_ID),
    SOLICITACAO_ADOCAO_ID   INTEGER NOT NULL,
    FOREIGN KEY (SOLICITACAO_ADOCAO_ID) REFERENCES SOLICITACAO_ADOCAO (SOLICITACAO_ADOCAO_ID),
    DATA_FIM_ADOCAO         DATE,
    DATA_FIM_ACOMPANHAMENTO DATE    NOT NULL
);

CREATE TABLE IF NOT EXISTS ACOMPANHAMENTO_ADOCAO
(
    ACOMPANHAMENTO_ADOCAO_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    DATA_ACOMPANHAMENTO      DATE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DESCRICAO                VARCHAR(240),
    FOTO                     BLOB    NOT NULL,
    ADOCAO_ID                INTEGER NOT NULL,
    FOREIGN KEY (ADOCAO_ID) REFERENCES ADOCAO (ADOCAO_ID)
);

CREATE TABLE IF NOT EXISTS LOG
(
    LOG_ID       INTEGER      NOT NULL PRIMARY KEY AUTOINCREMENT,
    USUARIO_ID   INTEGER,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID),
    USUARIO_NOME INTEGER,
    DATA         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ACAO         CHAR(1)      NOT NULL,
    DESCRICAO    VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS DICAS_NOTICIAS
(
    NOTICIA_ID   INTEGER   NOT NULL PRIMARY KEY AUTOINCREMENT,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CATEGORIA    CHAR(1),
    CONTEUDO     VARCHAR(500)
);

INSERT INTO DICAS_NOTICIAS(
  "CATEGORIA", "CONTEUDO"
)
VALUES (
        'E',
        "Gatos são legais"
       );

select * from DICAS_NOTICIAS;