-- CREATE
-- DATABASE MIAUDOTE;


CREATE TABLE USUARIO
(
    USUARIO_ID    INTEGER     NOT NULL PRIMARY KEY AUTOINCREMENT,

    NOME          VARCHAR(60) NOT NULL,
    CPF           VARCHAR(11) NOT NULL,
    EMAIL         VARCHAR(50) NOT NULL,
    SENHA         VARCHAR(60) NOT NULL,
    ENDERECO_ID   INT,
    FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO (ENDERECO_ID),
    CONTATO       VARCHAR(15),
    PERFIL_ACESSO CHAR(1)
);

CREATE TABLE PET
(
    PET_ID              INT         NOT NULL PRIMARY KEY AUTOINCREMENT,
    NOME                VARCHAR(50) NOT NULL,
    SEXO                CHAR(1)     NOT NULL,
    IDADE               INT,
    PORTE               CHAR(1),
    CASTRADO            CHAR(1),
    DATA_CADASTRO       DATE        NOT NULL DEFAULT CURRENT_DATE,
    DESCRICAO           VARCHAR(240),
    FOTO                BLOB,
    USUARIO_CADASTRO_ID INT         NOT NULL,
    FOREIGN KEY (USUARIO_CADASTRO_ID) REFERENCES USUARIO (USUARIO_ID)
);

CREATE TABLE ENDERECO
(
    ENDERECO_ID INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    ESTADO      VARCHAR(100),
    CIDADE      VARCHAR(100),
    BAIRRO      VARCHAR(100)
);

CREATE TABLE DOENCA
(
    DOENCA_ID INT         NOT NULL PRIMARY KEY AUTOINCREMENT,
    PET_ID    INT,
    FOREIGN KEY (PET_ID) REFERENCES PET (PET_ID),
    NOME      VARCHAR(60) NOT NULL,
    DESCRICAO VARCHAR(150)
);

CREATE TABLE SOLICITACAO_ADOCAO
(
    SOLICITACAO_ADOCAO_ID          INT       NOT NULL PRIMARY KEY AUTOINCREMENT,
    USER_RESPONSAVEL_ID            INT       NOT NULL,
    FOREIGN KEY (USER_RESPONSAVEL_ID) REFERENCES USUARIO (USUARIO_ID),
    USER_ADOTANTE_ID               INT       NOT NULL,
    FOREIGN KEY (USER_ADOTANTE_ID) REFERENCES USUARIO (USUARIO_ID),
    DATA_SOLICITACAO               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_RESPOSTA_USER_ADOTANTE    TIMESTAMP,
    RESPOSTA_USER_ADOTANTE         CHAR(1),
    DATA_RESPOSTA_USER_RESPONSAVEL TIMESTAMP,
    RESPOSTA_USER_RESPONSAVEL      CHAR(1),
    PET_ID                         INT       NOT NULL,
    FOREIGN KEY (PET_ID) REFERENCES PET (PET_ID)
);

CREATE TABLE ADOCAO
(
    ADOCAO_ID               INT  NOT NULL PRIMARY KEY AUTOINCREMENT,
    DATA_INICIO_ADOCAO      DATE NOT NULL DEFAULT CURRENT_DATE,
    USER_ADOCAO_ID          INT  NOT NULL,
    FOREIGN KEY (USER_ADOCAO_ID) REFERENCES USUARIO (USUARIO_ID),
    PET_ADOTADO_ID          INT  NOT NULL,
    FOREIGN KEY (PET_ADOTADO_ID) REFERENCES PET (PET_ID),
    SOLICITACAO_ADOCAO_ID   INT  NOT NULL,
    FOREIGN KEY (SOLICITACAO_ADOCAO_ID) REFERENCES SOLICITACAO_ADOCAO (SOLICITACAO_ADOCAO_ID),
    DATA_FIM_ADOCAO         DATE,
    DATA_FIM_ACOMPANHAMENTO DATE NOT NULL
);

CREATE TABLE ACOMPANHAMENTO_ADOCAO
(
    ACOMPANHAMENTO_ADOCAO_ID INT  NOT NULL PRIMARY KEY AUTOINCREMENT,
    DATA_ACOMPANHAMENTO      DATE NOT NULL DEFAULT CURRENT_DATE,
    DESCRICAO                VARCHAR(240),
    FOTO                     BLOB NOT NULL,
    ADOCAO_ID                INT  NOT NULL,
    FOREIGN KEY (ADOCAO_ID) REFERENCES ADOCAO (ADOCAO_ID)
);

CREATE TABLE LOG
(
    LOD_ID       INT          NOT NULL PRIMARY KEY AUTOINCREMENT,
    USUARIO_ID   INT,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID),
    USUARIO_NOME INT,
    DATA         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ACAO         CHAR(1)      NOT NULL,
    DESCRICAO    VARCHAR(500) NOT NULL
);

CREATE TABLE DICAS_NOTICIAS
(
    NOTICIA_ID   INT       NOT NULL PRIMARY KEY AUTOINCREMENT,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CATEGORIA    CHAR(1),
    CONTEUDO     VARCHAR(500)
);

-- CREATE TABLE TOKEN_LOGIN (

-- );

