# Generated by Django 4.2.11 on 2024-04-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="age",
            field=models.PositiveIntegerField(default=0, verbose_name="Age:"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="type",
            field=models.CharField(
                choices=[("C", "cachorro"), ("G", "gato")], max_length=8
            ),
        ),
    ]
