# Generated by Django 5.0.3 on 2024-05-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pet_age_alter_pet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='active',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pet',
            name='castrado',
            field=models.CharField(blank=True, db_column='CASTRADO', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='data_cadastro',
            field=models.DateField(blank=True, db_column='data_cadastro', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='descricao',
            field=models.TextField(blank=True, db_column='descricao', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, db_column='foto', null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='idade',
            field=models.IntegerField(blank=True, db_column='IDADE', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='nome',
            field=models.CharField(blank=True, db_column='NOME', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_id',
            field=models.IntegerField(blank=True, db_column='PET_ID', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='porte',
            field=models.CharField(blank=True, db_column='PORTE', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='sexo',
            field=models.CharField(blank=True, db_column='SEXO', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='usuario_cadastro_id',
            field=models.IntegerField(blank=True, db_column='usuario_cadastro_id', null=True),
        ),
    ]
