# Generated by Django 5.0.3 on 2024-05-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pet_active_remove_pet_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='id',
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_id',
            field=models.AutoField(db_column='PET_ID', primary_key=True, serialize=False),
        ),
    ]
