# Generated by Django 5.0.3 on 2024-05-14 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pet_id_alter_pet_pet_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
